"""initial

Revision ID: 45149cb03d01
Revises: 
Create Date: 2025-11-22 14:35:15.934057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45149cb03d01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khoan_thu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ngay_tao', sa.Date(), nullable=False),
    sa.Column('thoi_han', sa.Date(), nullable=True),
    sa.Column('ten_khoan_thu', sa.String(length=100), nullable=False),
    sa.Column('ban_buoc', sa.Boolean(), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nhan_khau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_ten', sa.String(length=100), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('gioi_tinh', sa.String(length=10), nullable=True),
    sa.Column('dan_toc', sa.String(length=30), nullable=True),
    sa.Column('ton_giao', sa.String(length=30), nullable=True),
    sa.Column('cccd', sa.String(length=20), nullable=True),
    sa.Column('ngay_cap', sa.Date(), nullable=True),
    sa.Column('noi_cap', sa.String(length=100), nullable=True),
    sa.Column('nghe_nghiep', sa.String(length=100), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cccd')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('vai_tro', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('ho_khau',
    sa.Column('so_ho_khau', sa.Integer(), nullable=False),
    sa.Column('so_nha', sa.String(length=50), nullable=True),
    sa.Column('duong', sa.String(length=50), nullable=True),
    sa.Column('phuong', sa.String(length=50), nullable=True),
    sa.Column('quan', sa.String(length=50), nullable=True),
    sa.Column('ngay_lam_ho_khau', sa.Date(), nullable=True),
    sa.Column('chu_ho_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chu_ho_id'], ['nhan_khau.id'], ),
    sa.PrimaryKeyConstraint('so_ho_khau'),
    sa.UniqueConstraint('chu_ho_id')
    )
    op.create_table('tam_tru_tam_vang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhan_khau_id', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.String(length=20), nullable=False),
    sa.Column('dia_chi', sa.String(length=100), nullable=True),
    sa.Column('thoi_gian', sa.Date(), nullable=False),
    sa.Column('noi_dung_de_nghi', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['nhan_khau_id'], ['nhan_khau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lich_su_ho_khau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhan_khau_id', sa.Integer(), nullable=False),
    sa.Column('ho_khau_id', sa.Integer(), nullable=False),
    sa.Column('loai_thay_doi', sa.Integer(), nullable=False),
    sa.Column('thoi_gian', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ho_khau_id'], ['ho_khau.so_ho_khau'], ),
    sa.ForeignKeyConstraint(['nhan_khau_id'], ['nhan_khau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nop_tien',
    sa.Column('ho_khau_id', sa.Integer(), nullable=False),
    sa.Column('khoan_thu_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_nop', sa.String(length=100), nullable=True),
    sa.Column('so_tien', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ngay_nop', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ho_khau_id'], ['ho_khau.so_ho_khau'], ),
    sa.ForeignKeyConstraint(['khoan_thu_id'], ['khoan_thu.id'], ),
    sa.PrimaryKeyConstraint('ho_khau_id', 'khoan_thu_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nop_tien')
    op.drop_table('lich_su_ho_khau')
    op.drop_table('tam_tru_tam_vang')
    op.drop_table('ho_khau')
    op.drop_table('users')
    op.drop_table('nhan_khau')
    op.drop_table('khoan_thu')
    # ### end Alembic commands ###
