"""initial models

Revision ID: 44dcc36163e9
Revises: 
Create Date: 2025-11-21 23:43:31.510489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44dcc36163e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khoanthu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NgayTao', sa.Date(), nullable=False),
    sa.Column('ThoiHan', sa.Date(), nullable=True),
    sa.Column('TenKhoanThu', sa.String(length=100), nullable=False),
    sa.Column('BatBuoc', sa.Boolean(), nullable=False),
    sa.Column('GhiChu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nhankhau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('HoTen', sa.String(length=100), nullable=False),
    sa.Column('NgaySinh', sa.Date(), nullable=True),
    sa.Column('GioiTinh', sa.String(length=10), nullable=True),
    sa.Column('DanToc', sa.String(length=30), nullable=True),
    sa.Column('TonGiao', sa.String(length=30), nullable=True),
    sa.Column('cccd', sa.String(length=20), nullable=True),
    sa.Column('NgayCap', sa.Date(), nullable=True),
    sa.Column('NoiCap', sa.String(length=100), nullable=True),
    sa.Column('NgheNghiep', sa.String(length=100), nullable=True),
    sa.Column('GhiChu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cccd')
    )
    op.create_table('users',
    sa.Column('UserName', sa.String(length=50), nullable=False),
    sa.Column('PassWord', sa.String(length=255), nullable=False),
    sa.Column('vaiTro', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('UserName')
    )
    op.create_table('hokhau',
    sa.Column('SoHoKhau', sa.Integer(), nullable=False),
    sa.Column('SoNha', sa.String(length=50), nullable=True),
    sa.Column('Duong', sa.String(length=50), nullable=True),
    sa.Column('Phuong', sa.String(length=50), nullable=True),
    sa.Column('Quan', sa.String(length=50), nullable=True),
    sa.Column('NgayLamHoKhau', sa.Date(), nullable=True),
    sa.Column('ChuHoId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ChuHoId'], ['nhankhau.id'], ),
    sa.PrimaryKeyConstraint('SoHoKhau'),
    sa.UniqueConstraint('ChuHoId')
    )
    op.create_table('tamtrutamvang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhanKhauId', sa.Integer(), nullable=False),
    sa.Column('trangThai', sa.String(length=20), nullable=False),
    sa.Column('diaChi', sa.String(length=100), nullable=True),
    sa.Column('thoiGian', sa.Date(), nullable=False),
    sa.Column('noiDungDeNghi', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['nhanKhauId'], ['nhankhau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lichsuhokhau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NhanKhauId', sa.Integer(), nullable=False),
    sa.Column('HoKhauId', sa.Integer(), nullable=False),
    sa.Column('LoaiThayDoi', sa.Integer(), nullable=False),
    sa.Column('ThoiGian', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['HoKhauId'], ['hokhau.SoHoKhau'], ),
    sa.ForeignKeyConstraint(['NhanKhauId'], ['nhankhau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noptien',
    sa.Column('HoKhauId', sa.Integer(), nullable=False),
    sa.Column('KhoanThuId', sa.Integer(), nullable=False),
    sa.Column('NguoiNop', sa.String(length=100), nullable=True),
    sa.Column('SoTien', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('NgayNop', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['HoKhauId'], ['hokhau.SoHoKhau'], ),
    sa.ForeignKeyConstraint(['KhoanThuId'], ['khoanthu.id'], ),
    sa.PrimaryKeyConstraint('HoKhauId', 'KhoanThuId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noptien')
    op.drop_table('lichsuhokhau')
    op.drop_table('tamtrutamvang')
    op.drop_table('hokhau')
    op.drop_table('users')
    op.drop_table('nhankhau')
    op.drop_table('khoanthu')
    # ### end Alembic commands ###
